global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - localhost:9095

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8085']
  
  - job_name: 'postgres-api-db'
    static_configs:
      - targets: ['postgres-exporter-api-db:9187']

  - job_name: 'postgres-radar-db'
    static_configs:
      - targets: ['postgres-exporter-radar-db:9188']

  - job_name: 'postgres-vote-db'
    static_configs:
      - targets: ['postgres-exporter-vote-db:9189']

